/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface CgDropdown {
        "multiple": boolean;
        "searchable": boolean;
    }
    interface CgDropdownOption {
        "hasCheckbox": boolean;
        "hidden": boolean;
        "optionId": string;
        "selected": boolean;
        "value": string;
    }
}
export interface CgDropdownOptionCustomEvent<T> extends CustomEvent<T> {
    detail: T;
    target: HTMLCgDropdownOptionElement;
}
declare global {
    interface HTMLCgDropdownElement extends Components.CgDropdown, HTMLStencilElement {
    }
    var HTMLCgDropdownElement: {
        prototype: HTMLCgDropdownElement;
        new (): HTMLCgDropdownElement;
    };
    interface HTMLCgDropdownOptionElement extends Components.CgDropdownOption, HTMLStencilElement {
    }
    var HTMLCgDropdownOptionElement: {
        prototype: HTMLCgDropdownOptionElement;
        new (): HTMLCgDropdownOptionElement;
    };
    interface HTMLElementTagNameMap {
        "cg-dropdown": HTMLCgDropdownElement;
        "cg-dropdown-option": HTMLCgDropdownOptionElement;
    }
}
declare namespace LocalJSX {
    interface CgDropdown {
        "multiple"?: boolean;
        "searchable"?: boolean;
    }
    interface CgDropdownOption {
        "hasCheckbox"?: boolean;
        "hidden"?: boolean;
        "onCgDropdownOptionChanged"?: (event: CgDropdownOptionCustomEvent<DropdownOptionChangedEventDetail>) => void;
        "optionId"?: string;
        "selected"?: boolean;
        "value"?: string;
    }
    interface IntrinsicElements {
        "cg-dropdown": CgDropdown;
        "cg-dropdown-option": CgDropdownOption;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "cg-dropdown": LocalJSX.CgDropdown & JSXBase.HTMLAttributes<HTMLCgDropdownElement>;
            "cg-dropdown-option": LocalJSX.CgDropdownOption & JSXBase.HTMLAttributes<HTMLCgDropdownOptionElement>;
        }
    }
}
